# Generated by Django 4.0.2 on 2022-02-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restapi',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
